theme: jekyll-theme-midnight
title: Welcome to TLanetteRose's Portfolio Homepage! 
description: I'm an Aspiring Web Developer and current Elementary Teacher! This is where you can explore my current projects as I continue to learn about computer coding! 
